#!/usr/bin/env python3
"""Build the public, crawlable GitHub Pages edition from reviewed public records."""
import html,json,re,shutil,os
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'docs'
DATA=json.loads((ROOT/'data/places.json').read_text())
BASE=os.environ.get('SITE_BASE_URL','https://napolyipizzeriakalauz.com/').rstrip('/')+'/'
assert BASE.startswith('https://')
CSS=(ROOT/'data/site.css').read_text().replace('pizza.png','pizza.jpg')
CSS+='''
[hidden]{display:none!important}.section{display:block}.site-main{max-width:1240px;margin:auto;padding:38px 28px 80px}.site-main h1{font-family:Georgia,serif;letter-spacing:-.04em;font-size:clamp(34px,4vw,52px);margin:0 0 16px}.lead{font-size:17px;line-height:1.65;color:#4b576b;max-width:820px}.breadcrumb{font-size:13px;color:#767f8e;margin-bottom:24px}.breadcrumb a{text-decoration:underline}.plain-card{background:#fff;border:1px solid #e1e4e9;border-radius:12px;padding:22px;margin:14px 0}.plain-card p{font-size:15px;line-height:1.65}.plain-card a,.prose a,.card-link{color:#15558c;text-decoration:underline;text-underline-offset:2px}.detail-meta{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.detail-meta .tag{letter-spacing:0}.prose{max-width:780px}.prose h2{font-family:Georgia,serif;font-size:27px;margin-top:34px}.prose p,.prose li{font-size:16px;line-height:1.75;color:#4b576b}.list{margin-top:22px}.filters{grid-template-columns:minmax(170px,1fr) minmax(140px,1fr) minmax(160px,1fr) auto auto}.filters button{height:46px}.card-link{display:inline-block;font-size:14px;font-weight:700;margin-top:12px}.card .card-body{min-height:174px}.card h2{font-size:17px;margin:0}.card .tag{display:inline-block}.link-row{display:flex;gap:16px;flex-wrap:wrap;margin-top:9px}.link-row a{font-size:14px}.site-tag{font-size:12px;background:#fff2d8;color:#7b541b;padding:6px 10px;border-radius:20px}.footer a{text-decoration:underline}.notice{border-left:4px solid #c79538;padding:14px 18px;background:#fff}.carousel-controls button:focus-visible,.apply:focus-visible,a:focus-visible{outline:3px solid #e9b963;outline-offset:3px}.photo-mock{aspect-ratio:1.55}.header .nav a.active{color:#a36b1e}@media(max-width:1000px){.filters{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.site-main{padding:30px 18px 60px}.filters{grid-template-columns:1fr}.header-inner{gap:12px}.nav{overflow-x:auto}.link-row{flex-direction:column;gap:8px}}
'''
CSS+='''
.photo-mock.venue-photo{position:relative;overflow:hidden}.venue-photo .venue-image{width:100%;height:100%;object-fit:cover;display:block}.venue-photo .photo-credit{position:absolute;bottom:0;left:0;right:0;background:#101928eb;color:#fff;padding:7px 9px;font-size:12px;line-height:1.4}.photo-credit a{color:#fff;text-decoration:underline}.photo-credit a:hover{color:#f1d293}.photo-credit a:first-child{white-space:nowrap;font-family:Arial,sans-serif;font-weight:400}
.association-badges{display:flex;flex-wrap:wrap;gap:7px;margin:8px 0}.association-badges a{border:1px solid #bac8d3;border-radius:20px;padding:4px 9px;color:#224e69;background:#eff7fa;font-size:12px;font-weight:700;text-decoration:none}.association-badges a:hover{text-decoration:underline}
'''
LABEL={'gold':'Arany minősítés','silver':'Ezüst minősítés','recommended':'Ajánlott','unrated':'Egyéb'}
DETAIL={
'Salve Basilica':'salve-basilica',
'Salve Pest':'salve-pest',
'Salve Budapart':'salve-budapart',
'Salve Pop Up':'salve-pop-up',
}

def e(x):return html.escape(str(x),quote=True)
def url(path=''):return BASE+path
def link(path,label):return f'<a href="{e(url(path))}">{e(label)}</a>'
def external(place):
 u=place['official_url']
 return f'<a href="{e(u)}" target="_blank" rel="noopener noreferrer">A pizzéria weboldala ↗</a>' if u else ''
def detail(place):
 slug=DETAIL.get(place['name'])
 return f'pizzeria/{slug}/' if slug else ''
def photo(place):return f'<div class="photo-mock venue-photo" data-place-name="{e(place["name"])}" data-place-city="{e(place["city"])}" data-place-address="{e(place["address"])}" role="img" aria-label="{e(place["name"])}: az éttermi fotó helye"><div class="photo-mark">NP</div><span>ÉTTERMI FOTÓ HELYE</span></div>'
def associations(place):
 badges=[]
 for field,label in [('fupi_recognition_url','FuPi-tábla ↗'),('avpn_url','AVPN-tag ↗')]:
  if place.get(field):badges.append(f'<a href="{e(place[field])}" target="_blank" rel="noopener noreferrer">{e(label)}</a>')
 return f'<div class="association-badges">{"".join(badges)}</div>' if badges else ''
def card(p):
 d=detail(p);status=' · '.join(x for x in ['Szezonális' if p['seasonal'] else '', 'Ellenőrzés alatt' if p['verify'] else '', 'Nincs elegendő online elérhető adat' if p['insufficient'] else ''] if x)
 name=link(d,p['name']) if d else e(p['name'])
 return f'<article class="card {p["grade"] if p["grade"] in ("gold","silver") else ""}" data-name="{e(p["name"].lower())}" data-city="{e(p["city"])}" data-grade="{e(p["grade"])}">{photo(p)}<div class="card-body"><div class="card-title"><h2>{name}</h2><span class="tag {e(p["grade"])}">{LABEL[p["grade"]]}</span></div><p>{e(p["city"])}{(' · '+e(p['address'])) if p['address'] else ''}</p>{associations(p)}<p class="card-status">{e(status)}</p><div class="link-row">{external(p)}</div></div></article>'

def jsonld(data):return '<script type="application/ld+json">'+json.dumps(data,ensure_ascii=False).replace('</','<\\/')+'</script>'
def wrap(path,title,description,body,active='',schema=None,noindex=False):
 nav=[('','Főoldal'),('pizzeriak/','Összes pizzéria'),('modszertan/','Módszertan'),('blog/','Blog'),('kapcsolat/','Kapcsolat')]
 navhtml=''.join(f'<a href="{e(url(p))}" class="{("active" if p==active else "")}">{e(n)}</a>' for p,n in nav)
 canonical=url(path)
 meta=f'<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(description)}"><link rel="canonical" href="{e(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{e(canonical)}">'
 if noindex:meta+='<meta name="robots" content="noindex,follow">'
 mark=jsonld(schema) if schema else ''
 content=f'''<!doctype html><html lang="hu"><head>{meta}<link rel="icon" href="{e(url('favicon.svg'))}" type="image/svg+xml"><style>{CSS}</style>{mark}<script defer src="{e(url('photo-config.js'))}"></script><script defer src="{e(url('venue-photos.js'))}"></script></head><body><header class="header"><div class="shell header-inner"><a href="{e(url())}" class="brand">NÁPOLYI <span>PIZZÉRIA</span> KALAUZ</a><nav class="nav" aria-label="Főmenü">{navhtml}</nav></div></header>{body}<footer class="footer"><div class="shell"><span>© 2026 Nápolyi Pizzéria Kalauz · A kalauz kiadója a Salve márkához kötődik.</span><span>{link('modszertan/','Módszertan')} · {link('adatkezeles/','Adatkezelés és feltételek')} · Utolsó adatgyűjtés: 2026. szeptember 26.</span></div></footer></body></html>'''
 target=OUT/path/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(content)
 return path

if OUT.exists():shutil.rmtree(OUT)
OUT.mkdir()
(OUT/'.nojekyll').write_text('')
(OUT/'CNAME').write_text('napolyipizzeriakalauz.com\n')
(OUT/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#182139"/><circle cx="32" cy="32" r="22" fill="#d8aa59"/><path d="M19 32c10-12 17-10 26 0-7 12-18 12-26 0" fill="#bb4a36"/></svg>')
shutil.copy(ROOT/'data/pizza.jpg',OUT/'pizza.jpg')
shutil.copy(ROOT/'data/venue-photos.js',OUT/'venue-photos.js')
shutil.copy(ROOT/'data/photo-config.js',OUT/'photo-config.js')
indexed=[]
# Home: visible content and links in initial HTML; carousel only enhances it.
gold=[p for p in DATA if p['grade']=='gold']
featured=gold[:3]
home=f'''<section class="intro"><div class="intro-copy"><div class="eyebrow">Országos pizzériakalauz</div><h1>Nápolyi pizza Magyarországon</h1><p>Fedezd fel a nápolyi pizzát kínáló helyeket Budapesten és vidéken. Kereshetsz település, név és minősítés szerint, külön telephelyekre bontva.</p></div><div class="intro-photo" role="img" aria-label="Nápolyi pizza illusztráció" style="background-image:url('{e(url('pizza.jpg'))}')"></div></section><main class="shell main"><div class="featured"><div><h2>Arany minősítésű helyek</h2><small>Lapozz a helyek között, vagy várd meg az automatikus váltást.</small></div><div class="carousel-controls"><button type="button" id="pick-prev" aria-label="Előző pizzériák">←</button><button type="button" id="pick-next" aria-label="Következő pizzériák">→</button></div></div><div id="picks" class="picks" aria-live="polite">{''.join(f'<article class="pick">{photo(p)}<div class="pick-content"><span class="pill">ARANY MINŐSÍTÉS</span><h3>{link(detail(p),p['name']) if detail(p) else e(p['name'])}</h3><p>{e(p['city'])}</p></div></article>' for p in featured)}</div><p class="carousel-note">Ha egy pizzériához nem találunk egyértelműen hozzá tartozó fotót, a képhely marad látható.</p></main>'''
# The carousel data is public, with no internal scoring.
cycle=gold
js=f'''<script>const picks={json.dumps([{'name':p['name'],'city':p['city'],'address':p['address'],'href':url(detail(p)) if detail(p) else None} for p in cycle],ensure_ascii=False)};let offset=0;const box=document.getElementById('picks');function draw(loadCarousel=false){{const n=innerWidth<700?1:innerWidth<1000?2:3,used=new Set(),items=[];for(let k=0;k<picks.length&&items.length<n;k++){{const p=picks[(offset+k)%picks.length];if(used.has(p.name))continue;used.add(p.name);items.push(p)}}box.replaceChildren(...items.map(p=>{{let a=document.createElement('article');a.className='pick';let mock=document.createElement('div');mock.className='photo-mock venue-photo';mock.dataset.placeName=p.name;mock.dataset.placeCity=p.city;mock.dataset.placeAddress=p.address;mock.setAttribute('role','img');mock.setAttribute('aria-label',p.name+': az éttermi fotó helye');mock.innerHTML='<div class="photo-mark">NP</div><span>ÉTTERMI FOTÓ HELYE</span>';let content=document.createElement('div');content.className='pick-content';let badge=document.createElement('span');badge.className='pill';badge.textContent='ARANY MINŐSÍTÉS';let name=document.createElement('h3');if(p.href){{let link=document.createElement('a');link.href=p.href;link.textContent=p.name;name.append(link)}}else name.textContent=p.name;let city=document.createElement('p');city.textContent=p.city;content.append(badge,name,city);a.append(mock,content);return a}}));document.dispatchEvent(new CustomEvent('venuephotos:refresh',{{detail:{{loadCarousel}}}}))}}function step(n,manual=false){{offset=(offset+n+picks.length)%picks.length;draw(manual)}}document.getElementById('pick-prev').onclick=()=>step(-1,true);document.getElementById('pick-next').onclick=()=>step(1,true);addEventListener('resize',draw);setInterval(()=>{{if(!document.hidden&&!box.matches(':hover'))step(1)}},5500);draw(true);</script>'''
home=home.replace('</main>',js+'</main>')
indexed.append(wrap('','Nápolyi Pizzéria Kalauz – pizzériák Magyarországon','Országos, kereshető nápolyi pizzériakalauz Budapesten és vidéken. Települések és minősítések, külön éttermi egységek.',home,'',{'@context':'https://schema.org','@type':'WebSite','name':'Nápolyi Pizzéria Kalauz','url':url(),'inLanguage':'hu-HU'}))
# Server-rendered all places; JS applies the user's filters and pagination after load.
CITIES=sorted({p['city'] for p in DATA if p['city']},key=str.casefold)
filter_html=f'''<form class="search-panel" id="filter-form"><h2>Pizzériák keresése</h2><div class="filters"><div class="field"><label for="name-search">Pizzéria neve</label><input id="name-search" type="search" placeholder="Név vagy névrészlet"></div><div class="field"><label for="city">Város</label><select id="city"><option value="">Minden város</option>{''.join(f'<option value="{e(x)}">{e(x)}</option>' for x in CITIES)}</select></div><div class="field"><label for="rating">Minősítés</label><select id="rating"><option value="">Minden minősítés</option>{''.join(f'<option value="{k}">{v}</option>' for k,v in LABEL.items())}</select></div><button type="submit" class="apply">Szűrés</button><button type="button" class="reset" id="clear">Szűrők törlése</button></div></form>'''
list_js='''<script>const form=document.getElementById('filter-form'),cards=[...document.querySelectorAll('#list article')],nameInput=document.getElementById('name-search'),cityInput=document.getElementById('city'),gradeInput=document.getElementById('rating');let selected={name:'',city:'',grade:''},page=1;const perPage=10;function show(){let matching=cards.filter(x=>(!selected.name||x.dataset.name.includes(selected.name))&&(!selected.city||x.dataset.city===selected.city)&&(!selected.grade||x.dataset.grade===selected.grade)),pages=Math.max(1,Math.ceil(matching.length/perPage));page=Math.min(page,pages);const subset=new Set(matching.slice((page-1)*perPage,page*perPage));cards.forEach(x=>x.hidden=!subset.has(x));document.getElementById('result-count').textContent=matching.length+' hely · 10 találat oldalanként';document.getElementById('page-info').textContent=page+' / '+pages+' oldal';document.getElementById('prev').disabled=page===1;document.getElementById('next').disabled=page===pages;document.getElementById('empty').hidden=matching.length!==0;document.dispatchEvent(new Event('venuephotos:refresh'))}form.addEventListener('submit',e=>{e.preventDefault();selected={name:nameInput.value.trim().toLocaleLowerCase('hu'),city:cityInput.value,grade:gradeInput.value};page=1;show()});document.getElementById('clear').onclick=()=>{form.reset();selected={name:'',city:'',grade:''};page=1;show()};document.getElementById('prev').onclick=()=>{page--;show();form.scrollIntoView({behavior:'smooth'})};document.getElementById('next').onclick=()=>{page++;show();form.scrollIntoView({behavior:'smooth'})};show();</script>'''
listing=f'''<main class="site-main"><div class="breadcrumb">{link('','Főoldal')} / Összes pizzéria</div><h1>Összes nápolyi pizzéria</h1><p class="lead">A jelenleg azonosított {len(DATA)} magyarországi telephely ábécérendben. Egy márka több címen működő egysége külön szerepel. Mindhárom mezőt üresen hagyva a teljes lista látszik; a szűrők tetszőlegesen kombinálhatók.</p><p>A <strong>FuPi-tábla</strong> a Magyar Pizza Szövetség <a href="https://fupihungary.hu/#pizzaterkep" target="_blank" rel="noopener noreferrer">pizzatérképén</a> szereplő, minőséget igazoló táblával elismert egységet jelöli; önmagában nem igazolja az étterem egyesületi tagságát. Az <strong>AVPN-tag</strong> az olasz szövetség nyilvános pizzériajegyzékében szereplő egységet jelöli. Ezek a kalauz saját minősítéseitől függetlenek. A jelölésekre kattintva megnyílik a forrás.</p>{filter_html}<section class="results"><p id="result-count">{len(DATA)} hely</p><div id="list" class="list">{''.join(map(card,sorted(DATA,key=lambda p:(p['name'].casefold(),p['city'].casefold()))))}</div><p id="empty" hidden>Nincs a szűrésnek megfelelő találat.</p><div class="pagination"><button id="prev" type="button">← Előző</button><span id="page-info"></span><button id="next" type="button">Következő →</button></div></section>{list_js}</main>'''
indexed.append(wrap('pizzeriak/','Nápolyi pizzériák Magyarországon – kereshető teljes lista','Nápolyi pizzériák ábécérendben, külön budapesti és vidéki telephelyekkel. Keresés pizzérianév, város és minősítés szerint.',listing,'pizzeriak/',{'@context':'https://schema.org','@type':'CollectionPage','name':'Nápolyi pizzériák Magyarországon','url':url('pizzeriak/'),'numberOfItems':len(DATA)}))
# Budapest overview and a distinct Basilica area guide.
bp=sorted([p for p in DATA if p['city']=='Budapest'],key=lambda x:x['name'].casefold())
bud=f'''<main class="site-main"><div class="breadcrumb">{link('','Főoldal')} / Budapest</div><h1>Nápolyi pizza Budapesten</h1><p class="lead">Budapesti pizzériák és külön telephelyek egy helyen. A belvárosi kereséshez érdemes a pontos címet is megnézni: az azonos márkanév alatt működő egységek különböző városrészekben lehetnek.</p><p>{link('budapest/bazilika-napolyi-pizza/','Pizzériák a Szent István-bazilika környékén')} · {link('pizzeriak/','Keresés az országos listában')}</p><div class="list">{''.join(map(card,bp))}</div></main>'''
indexed.append(wrap('budapest/','Nápolyi pizza Budapest – belvárosi és más budapesti pizzériák','Budapesti nápolyi pizzériák címmel és külön telephelyekkel. Belvárosi helyek és Szent István-bazilika környéki választék.',bud,'budapest/',{'@context':'https://schema.org','@type':'CollectionPage','name':'Nápolyi pizza Budapesten','url':url('budapest/'),'numberOfItems':len(bp)}))
near=[p for p in DATA if p['name'] in ('Salve Basilica','Forni di Napoli Bazilika')]
baz=f'''<main class="site-main prose"><div class="breadcrumb">{link('','Főoldal')} / {link('budapest/','Budapest')} / Bazilika</div><h1>Nápolyi pizza a Bazilika közelében</h1><p class="lead">A Szent István-bazilika környékén több, nápolyi pizzát kínáló hely is működik. A pontos cím alapján válassz, és az indulás előtt ellenőrizd a pizzéria saját oldalán az aktuális kínálatot.</p><h2>Két belvárosi telephely</h2><p>A Salve Basilica címe <strong>1065 Budapest, Bajcsy-Zsilinszky út 17.</strong> A Forni di Napoli Bazilika egysége az <strong>Október 6. utca 19.</strong> alatt található. A két pizzéria külön telephely és külön adatlap; a névben szereplő „Bazilika” egyiknél sem azonos címet jelent.</p><div class="list">{''.join(map(card,near))}</div><h2>Mit érdemes megnézni választás előtt?</h2><p>A nápolyi pizza sajátossága a puha, levegős perem és a magas hőfokon készülő tészta. A helyválasztásnál nézd meg a pizzéria aktuális étlapját és a helyben fogyasztásról szóló friss visszajelzéseket. A kalauzban szereplő minősítés online források értékelésén alapul; nem helyszíni kóstolás eredménye.</p><p>{link('budapest/','További budapesti helyek')} · {link('modszertan/','Hogyan készül a minősítés?')}</p></main>'''
indexed.append(wrap('budapest/bazilika-napolyi-pizza/','Nápolyi pizza a Bazilika közelében – Budapest belváros','Salve Basilica és Forni di Napoli Bazilika: nápolyi pizza Budapest belvárosában, a Szent István-bazilika környékén, ellenőrzött címekkel.',baz,'budapest/'))
# Individual verified branch pages, with visible relationship and no manufactured ratings.
for name,slug in DETAIL.items():
 p=next(x for x in DATA if x['name']==name)
 area='Budapest belvárosában, a Szent István-bazilika közelében' if name=='Salve Basilica' else ('Budapest IX. kerületében' if name=='Salve Pest' else 'Budapesten')
 extra='A Bajcsy-Zsilinszky úti egység néhány perc sétára van a Szent István-bazilikától.' if name=='Salve Basilica' else ''
 body=f'''<main class="site-main prose"><div class="breadcrumb">{link('','Főoldal')} / {link('budapest/','Budapest')} / {e(name)}</div><h1>{e(name)} – nápolyi pizza {e(area)}</h1><p class="lead">{e(name)} a Salve külön nyilvántartott budapesti egysége. {('Cím: '+e(p['address'])+', Budapest.') if p['address'] else ''} {e(extra)}</p><div class="detail-meta"><span class="tag {e(p['grade'])}">{LABEL[p['grade']]}</span>{'<span class="site-tag">Nincs elegendő online elérhető adat</span>' if p['insufficient'] else ''}</div>{associations(p)}<h2>Hely és forrás</h2><p>A pontos kínálat és a nyitvatartás a pizzéria saját oldalán ellenőrizhető. {external(p)} A kalauz minden Salve-egységet külön értékel, és a módszer minden telephelyre azonos.</p><p>{link('pizzeriak/','Az összes pizzéria')} · {link('budapest/','Budapesti helyek')} · {link('modszertan/','Módszertan')}</p></main>'''
 schema={'@context':'https://schema.org','@type':'Restaurant','name':name,'servesCuisine':'Nápolyi pizza','address':{'@type':'PostalAddress','streetAddress':p['address'],'addressLocality':'Budapest','addressCountry':'HU'},'url':p['official_url']} if p['address'] and p['official_url'] else None
 indexed.append(wrap(f'pizzeria/{slug}/',f'{name} – nápolyi pizza Budapest | Nápolyi Pizzéria Kalauz',f'{name}: külön budapesti telephely, cím és hivatkozás a pizzéria oldalára. {area}.',body,'budapest/',schema))
# Methodology from the live design, with no point values tied to a restaurant.
source=(ROOT.parent/'pizza-layout/dist/index.html').read_text()
section=re.search(r'<div class="shell section" id="modszertan">(.*?)</div><div class="shell section" id="blog">',source,re.S).group(1)
method=f'<main class="site-main prose"><div class="breadcrumb">{link("","Főoldal")} / Módszertan</div>{section}</main>'
indexed.append(wrap('modszertan/','Módszertan – hogyan értékeljük a nápolyi pizzériákat?','Online források, vendégvélemények és súlyozott szempontok. Félévenkénti felülvizsgálat, AI szerepe és az országos minősítések szabályai.',method,'modszertan/'))
wrap('blog/','Blog – Nápolyi Pizzéria Kalauz','Cikkek a magyarországi nápolyi pizzáról.',f'<main class="site-main prose"><h1>Blog</h1><p>A cikkek a szerkesztésük után jelennek meg.</p>{link("pizzeriak/","Pizzériák keresése")}</main>','blog/',noindex=True)
wrap('kapcsolat/','Kapcsolat – Nápolyi Pizzéria Kalauz','Kapcsolati oldal.',f'<main class="site-main prose"><h1>Kapcsolat</h1><p>A kapcsolati adatok a végleges megjelenéskor kerülnek ide.</p>{link("pizzeriak/","Pizzériák keresése")}</main>','kapcsolat/',noindex=True)
privacy='''<main class="site-main prose"><h1>Adatkezelés és felhasználási feltételek</h1><h2>Étteremfotók</h2><p>Az étteremfotók megjelenítéséhez az oldal a Google Maps Platform Places szolgáltatását használhatja. Ekkor a böngésző kapcsolatot létesít a Google szervereivel. A fotók mellett feltüntetjük a Google Maps hivatkozását és a rendelkezésre álló szerzői megjelölést. Az egyezés nélkül maradt pizzériákhoz nem jelenítünk meg másik helytől származó fotót.</p><h2>Adatkezelési tájékoztatás</h2><p>A Google szolgáltatásainak adatkezeléséről a <a href="https://policies.google.com/privacy" rel="noopener noreferrer" target="_blank">Google adatvédelmi irányelveiben</a> olvashatsz. A kalauz nem tárolja a Google fotóinak képállományát és ideiglenes fotócímét.</p><h2>Felhasználási feltételek</h2><p>A Google Mapsből származó tartalom használatára a <a href="https://policies.google.com/terms" rel="noopener noreferrer" target="_blank">Google szolgáltatási feltételei</a> és a <a href="https://www.google.com/help/terms_maps/" rel="noopener noreferrer" target="_blank">Google Maps kiegészítő feltételei</a> is vonatkoznak. A pizzériák adatai változhatnak; az aktuális kínálatot a helyek saját oldalán érdemes ellenőrizni.</p></main>'''
indexed.append(wrap('adatkezeles/','Adatkezelés és feltételek – Nápolyi Pizzéria Kalauz','A Google Mapsből megjelenített étteremfotók forrása, az adatkezelési tájékoztatás és felhasználási feltételek.',privacy,'adatkezeles/'))
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+url('sitemap.xml')+'\n')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{xml_escape(url(p))}</loc><lastmod>2026-09-26</lastmod></url>\n' for p in indexed)+'</urlset>\n')
print(f'Built {len(indexed)} indexable pages, {len(DATA)} places, {sum(bool(p["official_url"]) for p in DATA)} outbound venue links: {BASE}')
